### ISSUE TITLE
ffield_generator module missing

### ISSUE THREAD

**Issue by holyjoly** [mertyigit/INDEEDopt#2]
Hi, this repository appears to be missing the ffield_generator module. Any plans to add it? Thanks.

**Comment by mertyigit** [comment]
Hi, 

The ffield_generator is the folder that the whole script should be copied into. I see you closed the issue but let me know if you need help.

**Comment by holyjoly** [comment]
Hi,
That's helpful. I closed the issue when we noticed that the routines from ffield_generator are distributed in the various source files, but hadn't understood the folder thing. Is there an example you would be willing to provide?
Many thanks!

**Comment by mertyigit** [comment]
I have uploaded a zip file names as example_github.zip, which includes an example. There is README file in it that explains how to prepare the INDEEDopt folder and start the code. Let me know if you have any difficulties.

**Comment by miroi** [comment]
Well, I just open new issue, concerning this closed one. So "The ffield_generator is the folder that the whole script should be copied into" ?
